"""add username field to user

Revision ID: 10_add_username_field
Revises: 9_add_notification_preferences
Create Date: 2025-11-14 20:30:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '10_add_username_field'
down_revision = '9_add_notification_preferences'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Agregar campo username al modelo User
    op.add_column('user', sa.Column('username', sa.String(length=50), nullable=True))

    # Generar usernames únicos para usuarios existentes basados en el email
    # Extrae la parte antes del @ del email como username inicial
    op.execute("""
        UPDATE "user"
        SET username = split_part(email, '@', 1)
        WHERE username IS NULL
    """)

    # Crear índice único para el campo username
    op.create_unique_constraint('uq_user_username', 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Eliminar constraint único
    op.drop_constraint('uq_user_username', 'user', type_='unique')

    # Eliminar campo username
    op.drop_column('user', 'username')
    # ### end Alembic commands ###
