"""add profile and location fields

Revision ID: 4_add_profile_fields
Revises: 15df9a0da535
Create Date: 2025-11-13 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4_add_profile_fields'
down_revision = '15df9a0da535'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Agregar campos de perfil
    op.add_column('user', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('skills', sa.ARRAY(sa.String()), nullable=True))

    # Agregar campos de ubicación
    op.add_column('user', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('user', sa.Column('city', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('country', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Eliminar campos de ubicación
    op.drop_column('user', 'longitude')
    op.drop_column('user', 'latitude')
    op.drop_column('user', 'country')
    op.drop_column('user', 'city')
    op.drop_column('user', 'address')

    # Eliminar campos de perfil
    op.drop_column('user', 'skills')
    op.drop_column('user', 'bio')
    # ### end Alembic commands ###
