"""add category, portfolio and messaging system

Revision ID: 5_add_features
Revises: 4_add_profile_fields
Create Date: 2025-11-13 14:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5_add_features'
down_revision = '4_add_profile_fields'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Agregar campo category a user
    op.add_column('user', sa.Column('category', sa.String(length=50), nullable=True))

    # Crear tabla portfolio
    op.create_table('portfolio',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('media_type', sa.String(length=50), nullable=False),
        sa.Column('media_url', sa.String(length=500), nullable=False),
        sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
        sa.Column('order', sa.Integer(), nullable=True),
        sa.Column('createdAt', sa.DateTime(), nullable=True),
        sa.Column('updatedAt', sa.DateTime(), nullable=True),
        sa.Column('deletedAt', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # Crear tabla conversation
    op.create_table('conversation',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('participant1_id', sa.Integer(), nullable=False),
        sa.Column('participant2_id', sa.Integer(), nullable=False),
        sa.Column('last_message_at', sa.DateTime(), nullable=True),
        sa.Column('createdAt', sa.DateTime(), nullable=True),
        sa.Column('updatedAt', sa.DateTime(), nullable=True),
        sa.Column('deletedAt', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['participant1_id'], ['user.id'], ),
        sa.ForeignKeyConstraint(['participant2_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('participant1_id', 'participant2_id', name='unique_conversation')
    )

    # Crear tabla message
    op.create_table('message',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('conversation_id', sa.Integer(), nullable=False),
        sa.Column('sender_id', sa.Integer(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('is_read', sa.Boolean(), nullable=False),
        sa.Column('read_at', sa.DateTime(), nullable=True),
        sa.Column('createdAt', sa.DateTime(), nullable=True),
        sa.Column('updatedAt', sa.DateTime(), nullable=True),
        sa.Column('deletedAt', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
        sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Eliminar tablas
    op.drop_table('message')
    op.drop_table('conversation')
    op.drop_table('portfolio')

    # Eliminar campo category
    op.drop_column('user', 'category')
    # ### end Alembic commands ###
