"""add reviews and saved search

Revision ID: 7_add_reviews_and_search
Revises: 6_add_notifications
Create Date: 2025-11-14 16:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7_add_reviews_and_search'
down_revision = '6_add_notifications'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Crear tabla review
    op.create_table('review',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('reviewer_id', sa.Integer(), nullable=False),
        sa.Column('reviewee_id', sa.Integer(), nullable=False),
        sa.Column('rating', sa.Integer(), nullable=False),
        sa.Column('comment', sa.Text(), nullable=True),
        sa.Column('createdAt', sa.DateTime(), nullable=True),
        sa.Column('updatedAt', sa.DateTime(), nullable=True),
        sa.Column('deletedAt', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['reviewer_id'], ['user.id'], ),
        sa.ForeignKeyConstraint(['reviewee_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('reviewer_id', 'reviewee_id', name='unique_review_per_user'),
        sa.CheckConstraint('rating >= 1 AND rating <= 5', name='valid_rating_range'),
        sa.CheckConstraint('reviewer_id != reviewee_id', name='no_self_review')
    )

    # Crear tabla saved_search
    op.create_table('saved_search',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('search_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('createdAt', sa.DateTime(), nullable=True),
        sa.Column('updatedAt', sa.DateTime(), nullable=True),
        sa.Column('deletedAt', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Eliminar tablas
    op.drop_table('saved_search')
    op.drop_table('review')
    # ### end Alembic commands ###
