"""add notification preferences to user

Revision ID: 9_add_notification_preferences
Revises: 8_add_events_projects_security
Create Date: 2025-11-14 20:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9_add_notification_preferences'
down_revision = '8_add_events_projects_security'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Agregar campos de notificaciones al modelo User
    op.add_column('user', sa.Column('email_notifications', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('user', sa.Column('push_subscription', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Eliminar campos de notificaciones
    op.drop_column('user', 'push_subscription')
    op.drop_column('user', 'email_notifications')
    # ### end Alembic commands ###
