/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root.lazy'
import { Route as LoginImport } from './routes/login'
import { Route as AuthImport } from './routes/auth'
import { Route as LoginIndexRouteImport } from './routes/login/index.route'
import { Route as AuthUserImport } from './routes/auth/user'
import { Route as AuthSettingsImport } from './routes/auth/settings'
import { Route as AuthProjectsImport } from './routes/auth/projects'
import { Route as AuthEventsImport } from './routes/auth/events'
import { Route as AuthSuperadminDashboardImport } from './routes/auth/superadmin/dashboard'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const RegisterCreateAccountLazyImport = createFileRoute(
  '/register/create-account',
)()
const LoginResetPasswordLazyImport = createFileRoute('/login/reset-password')()
const LoginRecoverPasswordLazyImport = createFileRoute(
  '/login/recover-password',
)()
const AuthSupportLazyImport = createFileRoute('/auth/support')()
const AuthSearchLazyImport = createFileRoute('/auth/search')()
const AuthMessagesLazyImport = createFileRoute('/auth/messages')()
const AuthHomeLazyImport = createFileRoute('/auth/home')()
const AuthFeedbackLazyImport = createFileRoute('/auth/feedback')()
const AuthProjectsIndexLazyImport = createFileRoute('/auth/projects/')()
const AuthEventsIndexLazyImport = createFileRoute('/auth/events/')()
const AuthUserProfileLazyImport = createFileRoute('/auth/user/profile')()
const AuthUserMapLazyImport = createFileRoute('/auth/user/map')()
const AuthUserUsernameLazyImport = createFileRoute('/auth/user/$username')()
const AuthSettingsPrivacyLazyImport = createFileRoute(
  '/auth/settings/privacy',
)()
const AuthSettingsNotificationsLazyImport = createFileRoute(
  '/auth/settings/notifications',
)()
const AuthProjectsMyLazyImport = createFileRoute('/auth/projects/my')()
const AuthProjectsCreateLazyImport = createFileRoute('/auth/projects/create')()
const AuthProjectsIdLazyImport = createFileRoute('/auth/projects/$id')()
const AuthEventsMyLazyImport = createFileRoute('/auth/events/my')()
const AuthEventsCreateLazyImport = createFileRoute('/auth/events/create')()
const AuthEventsIdLazyImport = createFileRoute('/auth/events/$id')()

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const LoginIndexRouteRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRoute,
} as any)

const RegisterCreateAccountLazyRoute = RegisterCreateAccountLazyImport.update({
  id: '/register/create-account',
  path: '/register/create-account',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/register/create-account.lazy').then((d) => d.Route),
)

const LoginResetPasswordLazyRoute = LoginResetPasswordLazyImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => LoginRoute,
} as any).lazy(() =>
  import('./routes/login/reset-password.lazy').then((d) => d.Route),
)

const LoginRecoverPasswordLazyRoute = LoginRecoverPasswordLazyImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => LoginRoute,
} as any).lazy(() =>
  import('./routes/login/recover-password.lazy').then((d) => d.Route),
)

const AuthSupportLazyRoute = AuthSupportLazyImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/auth/support.lazy').then((d) => d.Route))

const AuthSearchLazyRoute = AuthSearchLazyImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/auth/search.lazy').then((d) => d.Route))

const AuthMessagesLazyRoute = AuthMessagesLazyImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/auth/messages.lazy').then((d) => d.Route))

const AuthHomeLazyRoute = AuthHomeLazyImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/auth/home.lazy').then((d) => d.Route))

const AuthFeedbackLazyRoute = AuthFeedbackLazyImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/auth/feedback.lazy').then((d) => d.Route))

const AuthUserRoute = AuthUserImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => AuthRoute,
} as any)

const AuthSettingsRoute = AuthSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)

const AuthProjectsRoute = AuthProjectsImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthRoute,
} as any)

const AuthEventsRoute = AuthEventsImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthRoute,
} as any)

const AuthProjectsIndexLazyRoute = AuthProjectsIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthProjectsRoute,
} as any).lazy(() =>
  import('./routes/auth/projects/index.lazy').then((d) => d.Route),
)

const AuthEventsIndexLazyRoute = AuthEventsIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthEventsRoute,
} as any).lazy(() =>
  import('./routes/auth/events/index.lazy').then((d) => d.Route),
)

const AuthUserProfileLazyRoute = AuthUserProfileLazyImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthUserRoute,
} as any).lazy(() =>
  import('./routes/auth/user/profile.lazy').then((d) => d.Route),
)

const AuthUserMapLazyRoute = AuthUserMapLazyImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthUserRoute,
} as any).lazy(() => import('./routes/auth/user/map.lazy').then((d) => d.Route))

const AuthUserUsernameLazyRoute = AuthUserUsernameLazyImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => AuthUserRoute,
} as any).lazy(() =>
  import('./routes/auth/user/$username.lazy').then((d) => d.Route),
)

const AuthSettingsPrivacyLazyRoute = AuthSettingsPrivacyLazyImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AuthSettingsRoute,
} as any).lazy(() =>
  import('./routes/auth/settings/privacy.lazy').then((d) => d.Route),
)

const AuthSettingsNotificationsLazyRoute =
  AuthSettingsNotificationsLazyImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthSettingsRoute,
  } as any).lazy(() =>
    import('./routes/auth/settings/notifications.lazy').then((d) => d.Route),
  )

const AuthProjectsMyLazyRoute = AuthProjectsMyLazyImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => AuthProjectsRoute,
} as any).lazy(() =>
  import('./routes/auth/projects/my.lazy').then((d) => d.Route),
)

const AuthProjectsCreateLazyRoute = AuthProjectsCreateLazyImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthProjectsRoute,
} as any).lazy(() =>
  import('./routes/auth/projects/create.lazy').then((d) => d.Route),
)

const AuthProjectsIdLazyRoute = AuthProjectsIdLazyImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthProjectsRoute,
} as any).lazy(() =>
  import('./routes/auth/projects/$id.lazy').then((d) => d.Route),
)

const AuthEventsMyLazyRoute = AuthEventsMyLazyImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => AuthEventsRoute,
} as any).lazy(() =>
  import('./routes/auth/events/my.lazy').then((d) => d.Route),
)

const AuthEventsCreateLazyRoute = AuthEventsCreateLazyImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthEventsRoute,
} as any).lazy(() =>
  import('./routes/auth/events/create.lazy').then((d) => d.Route),
)

const AuthEventsIdLazyRoute = AuthEventsIdLazyImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthEventsRoute,
} as any).lazy(() =>
  import('./routes/auth/events/$id.lazy').then((d) => d.Route),
)

const AuthSuperadminDashboardRoute = AuthSuperadminDashboardImport.update({
  id: '/superadmin/dashboard',
  path: '/superadmin/dashboard',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/events': {
      id: '/auth/events'
      path: '/events'
      fullPath: '/auth/events'
      preLoaderRoute: typeof AuthEventsImport
      parentRoute: typeof AuthImport
    }
    '/auth/projects': {
      id: '/auth/projects'
      path: '/projects'
      fullPath: '/auth/projects'
      preLoaderRoute: typeof AuthProjectsImport
      parentRoute: typeof AuthImport
    }
    '/auth/settings': {
      id: '/auth/settings'
      path: '/settings'
      fullPath: '/auth/settings'
      preLoaderRoute: typeof AuthSettingsImport
      parentRoute: typeof AuthImport
    }
    '/auth/user': {
      id: '/auth/user'
      path: '/user'
      fullPath: '/auth/user'
      preLoaderRoute: typeof AuthUserImport
      parentRoute: typeof AuthImport
    }
    '/auth/feedback': {
      id: '/auth/feedback'
      path: '/feedback'
      fullPath: '/auth/feedback'
      preLoaderRoute: typeof AuthFeedbackLazyImport
      parentRoute: typeof AuthImport
    }
    '/auth/home': {
      id: '/auth/home'
      path: '/home'
      fullPath: '/auth/home'
      preLoaderRoute: typeof AuthHomeLazyImport
      parentRoute: typeof AuthImport
    }
    '/auth/messages': {
      id: '/auth/messages'
      path: '/messages'
      fullPath: '/auth/messages'
      preLoaderRoute: typeof AuthMessagesLazyImport
      parentRoute: typeof AuthImport
    }
    '/auth/search': {
      id: '/auth/search'
      path: '/search'
      fullPath: '/auth/search'
      preLoaderRoute: typeof AuthSearchLazyImport
      parentRoute: typeof AuthImport
    }
    '/auth/support': {
      id: '/auth/support'
      path: '/support'
      fullPath: '/auth/support'
      preLoaderRoute: typeof AuthSupportLazyImport
      parentRoute: typeof AuthImport
    }
    '/login/recover-password': {
      id: '/login/recover-password'
      path: '/recover-password'
      fullPath: '/login/recover-password'
      preLoaderRoute: typeof LoginRecoverPasswordLazyImport
      parentRoute: typeof LoginImport
    }
    '/login/reset-password': {
      id: '/login/reset-password'
      path: '/reset-password'
      fullPath: '/login/reset-password'
      preLoaderRoute: typeof LoginResetPasswordLazyImport
      parentRoute: typeof LoginImport
    }
    '/register/create-account': {
      id: '/register/create-account'
      path: '/register/create-account'
      fullPath: '/register/create-account'
      preLoaderRoute: typeof RegisterCreateAccountLazyImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginImport
    }
    '/auth/superadmin/dashboard': {
      id: '/auth/superadmin/dashboard'
      path: '/superadmin/dashboard'
      fullPath: '/auth/superadmin/dashboard'
      preLoaderRoute: typeof AuthSuperadminDashboardImport
      parentRoute: typeof AuthImport
    }
    '/auth/events/$id': {
      id: '/auth/events/$id'
      path: '/$id'
      fullPath: '/auth/events/$id'
      preLoaderRoute: typeof AuthEventsIdLazyImport
      parentRoute: typeof AuthEventsImport
    }
    '/auth/events/create': {
      id: '/auth/events/create'
      path: '/create'
      fullPath: '/auth/events/create'
      preLoaderRoute: typeof AuthEventsCreateLazyImport
      parentRoute: typeof AuthEventsImport
    }
    '/auth/events/my': {
      id: '/auth/events/my'
      path: '/my'
      fullPath: '/auth/events/my'
      preLoaderRoute: typeof AuthEventsMyLazyImport
      parentRoute: typeof AuthEventsImport
    }
    '/auth/projects/$id': {
      id: '/auth/projects/$id'
      path: '/$id'
      fullPath: '/auth/projects/$id'
      preLoaderRoute: typeof AuthProjectsIdLazyImport
      parentRoute: typeof AuthProjectsImport
    }
    '/auth/projects/create': {
      id: '/auth/projects/create'
      path: '/create'
      fullPath: '/auth/projects/create'
      preLoaderRoute: typeof AuthProjectsCreateLazyImport
      parentRoute: typeof AuthProjectsImport
    }
    '/auth/projects/my': {
      id: '/auth/projects/my'
      path: '/my'
      fullPath: '/auth/projects/my'
      preLoaderRoute: typeof AuthProjectsMyLazyImport
      parentRoute: typeof AuthProjectsImport
    }
    '/auth/settings/notifications': {
      id: '/auth/settings/notifications'
      path: '/notifications'
      fullPath: '/auth/settings/notifications'
      preLoaderRoute: typeof AuthSettingsNotificationsLazyImport
      parentRoute: typeof AuthSettingsImport
    }
    '/auth/settings/privacy': {
      id: '/auth/settings/privacy'
      path: '/privacy'
      fullPath: '/auth/settings/privacy'
      preLoaderRoute: typeof AuthSettingsPrivacyLazyImport
      parentRoute: typeof AuthSettingsImport
    }
    '/auth/user/$username': {
      id: '/auth/user/$username'
      path: '/$username'
      fullPath: '/auth/user/$username'
      preLoaderRoute: typeof AuthUserUsernameLazyImport
      parentRoute: typeof AuthUserImport
    }
    '/auth/user/map': {
      id: '/auth/user/map'
      path: '/map'
      fullPath: '/auth/user/map'
      preLoaderRoute: typeof AuthUserMapLazyImport
      parentRoute: typeof AuthUserImport
    }
    '/auth/user/profile': {
      id: '/auth/user/profile'
      path: '/profile'
      fullPath: '/auth/user/profile'
      preLoaderRoute: typeof AuthUserProfileLazyImport
      parentRoute: typeof AuthUserImport
    }
    '/auth/events/': {
      id: '/auth/events/'
      path: '/'
      fullPath: '/auth/events/'
      preLoaderRoute: typeof AuthEventsIndexLazyImport
      parentRoute: typeof AuthEventsImport
    }
    '/auth/projects/': {
      id: '/auth/projects/'
      path: '/'
      fullPath: '/auth/projects/'
      preLoaderRoute: typeof AuthProjectsIndexLazyImport
      parentRoute: typeof AuthProjectsImport
    }
  }
}

// Create and export the route tree

interface AuthEventsRouteChildren {
  AuthEventsIdLazyRoute: typeof AuthEventsIdLazyRoute
  AuthEventsCreateLazyRoute: typeof AuthEventsCreateLazyRoute
  AuthEventsMyLazyRoute: typeof AuthEventsMyLazyRoute
  AuthEventsIndexLazyRoute: typeof AuthEventsIndexLazyRoute
}

const AuthEventsRouteChildren: AuthEventsRouteChildren = {
  AuthEventsIdLazyRoute: AuthEventsIdLazyRoute,
  AuthEventsCreateLazyRoute: AuthEventsCreateLazyRoute,
  AuthEventsMyLazyRoute: AuthEventsMyLazyRoute,
  AuthEventsIndexLazyRoute: AuthEventsIndexLazyRoute,
}

const AuthEventsRouteWithChildren = AuthEventsRoute._addFileChildren(
  AuthEventsRouteChildren,
)

interface AuthProjectsRouteChildren {
  AuthProjectsIdLazyRoute: typeof AuthProjectsIdLazyRoute
  AuthProjectsCreateLazyRoute: typeof AuthProjectsCreateLazyRoute
  AuthProjectsMyLazyRoute: typeof AuthProjectsMyLazyRoute
  AuthProjectsIndexLazyRoute: typeof AuthProjectsIndexLazyRoute
}

const AuthProjectsRouteChildren: AuthProjectsRouteChildren = {
  AuthProjectsIdLazyRoute: AuthProjectsIdLazyRoute,
  AuthProjectsCreateLazyRoute: AuthProjectsCreateLazyRoute,
  AuthProjectsMyLazyRoute: AuthProjectsMyLazyRoute,
  AuthProjectsIndexLazyRoute: AuthProjectsIndexLazyRoute,
}

const AuthProjectsRouteWithChildren = AuthProjectsRoute._addFileChildren(
  AuthProjectsRouteChildren,
)

interface AuthSettingsRouteChildren {
  AuthSettingsNotificationsLazyRoute: typeof AuthSettingsNotificationsLazyRoute
  AuthSettingsPrivacyLazyRoute: typeof AuthSettingsPrivacyLazyRoute
}

const AuthSettingsRouteChildren: AuthSettingsRouteChildren = {
  AuthSettingsNotificationsLazyRoute: AuthSettingsNotificationsLazyRoute,
  AuthSettingsPrivacyLazyRoute: AuthSettingsPrivacyLazyRoute,
}

const AuthSettingsRouteWithChildren = AuthSettingsRoute._addFileChildren(
  AuthSettingsRouteChildren,
)

interface AuthUserRouteChildren {
  AuthUserUsernameLazyRoute: typeof AuthUserUsernameLazyRoute
  AuthUserMapLazyRoute: typeof AuthUserMapLazyRoute
  AuthUserProfileLazyRoute: typeof AuthUserProfileLazyRoute
}

const AuthUserRouteChildren: AuthUserRouteChildren = {
  AuthUserUsernameLazyRoute: AuthUserUsernameLazyRoute,
  AuthUserMapLazyRoute: AuthUserMapLazyRoute,
  AuthUserProfileLazyRoute: AuthUserProfileLazyRoute,
}

const AuthUserRouteWithChildren = AuthUserRoute._addFileChildren(
  AuthUserRouteChildren,
)

interface AuthRouteChildren {
  AuthEventsRoute: typeof AuthEventsRouteWithChildren
  AuthProjectsRoute: typeof AuthProjectsRouteWithChildren
  AuthSettingsRoute: typeof AuthSettingsRouteWithChildren
  AuthUserRoute: typeof AuthUserRouteWithChildren
  AuthFeedbackLazyRoute: typeof AuthFeedbackLazyRoute
  AuthHomeLazyRoute: typeof AuthHomeLazyRoute
  AuthMessagesLazyRoute: typeof AuthMessagesLazyRoute
  AuthSearchLazyRoute: typeof AuthSearchLazyRoute
  AuthSupportLazyRoute: typeof AuthSupportLazyRoute
  AuthSuperadminDashboardRoute: typeof AuthSuperadminDashboardRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthEventsRoute: AuthEventsRouteWithChildren,
  AuthProjectsRoute: AuthProjectsRouteWithChildren,
  AuthSettingsRoute: AuthSettingsRouteWithChildren,
  AuthUserRoute: AuthUserRouteWithChildren,
  AuthFeedbackLazyRoute: AuthFeedbackLazyRoute,
  AuthHomeLazyRoute: AuthHomeLazyRoute,
  AuthMessagesLazyRoute: AuthMessagesLazyRoute,
  AuthSearchLazyRoute: AuthSearchLazyRoute,
  AuthSupportLazyRoute: AuthSupportLazyRoute,
  AuthSuperadminDashboardRoute: AuthSuperadminDashboardRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface LoginRouteChildren {
  LoginRecoverPasswordLazyRoute: typeof LoginRecoverPasswordLazyRoute
  LoginResetPasswordLazyRoute: typeof LoginResetPasswordLazyRoute
  LoginIndexRouteRoute: typeof LoginIndexRouteRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginRecoverPasswordLazyRoute: LoginRecoverPasswordLazyRoute,
  LoginResetPasswordLazyRoute: LoginResetPasswordLazyRoute,
  LoginIndexRouteRoute: LoginIndexRouteRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/auth/events': typeof AuthEventsRouteWithChildren
  '/auth/projects': typeof AuthProjectsRouteWithChildren
  '/auth/settings': typeof AuthSettingsRouteWithChildren
  '/auth/user': typeof AuthUserRouteWithChildren
  '/auth/feedback': typeof AuthFeedbackLazyRoute
  '/auth/home': typeof AuthHomeLazyRoute
  '/auth/messages': typeof AuthMessagesLazyRoute
  '/auth/search': typeof AuthSearchLazyRoute
  '/auth/support': typeof AuthSupportLazyRoute
  '/login/recover-password': typeof LoginRecoverPasswordLazyRoute
  '/login/reset-password': typeof LoginResetPasswordLazyRoute
  '/register/create-account': typeof RegisterCreateAccountLazyRoute
  '/login/': typeof LoginIndexRouteRoute
  '/auth/superadmin/dashboard': typeof AuthSuperadminDashboardRoute
  '/auth/events/$id': typeof AuthEventsIdLazyRoute
  '/auth/events/create': typeof AuthEventsCreateLazyRoute
  '/auth/events/my': typeof AuthEventsMyLazyRoute
  '/auth/projects/$id': typeof AuthProjectsIdLazyRoute
  '/auth/projects/create': typeof AuthProjectsCreateLazyRoute
  '/auth/projects/my': typeof AuthProjectsMyLazyRoute
  '/auth/settings/notifications': typeof AuthSettingsNotificationsLazyRoute
  '/auth/settings/privacy': typeof AuthSettingsPrivacyLazyRoute
  '/auth/user/$username': typeof AuthUserUsernameLazyRoute
  '/auth/user/map': typeof AuthUserMapLazyRoute
  '/auth/user/profile': typeof AuthUserProfileLazyRoute
  '/auth/events/': typeof AuthEventsIndexLazyRoute
  '/auth/projects/': typeof AuthProjectsIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/auth': typeof AuthRouteWithChildren
  '/auth/settings': typeof AuthSettingsRouteWithChildren
  '/auth/user': typeof AuthUserRouteWithChildren
  '/auth/feedback': typeof AuthFeedbackLazyRoute
  '/auth/home': typeof AuthHomeLazyRoute
  '/auth/messages': typeof AuthMessagesLazyRoute
  '/auth/search': typeof AuthSearchLazyRoute
  '/auth/support': typeof AuthSupportLazyRoute
  '/login/recover-password': typeof LoginRecoverPasswordLazyRoute
  '/login/reset-password': typeof LoginResetPasswordLazyRoute
  '/register/create-account': typeof RegisterCreateAccountLazyRoute
  '/login': typeof LoginIndexRouteRoute
  '/auth/superadmin/dashboard': typeof AuthSuperadminDashboardRoute
  '/auth/events/$id': typeof AuthEventsIdLazyRoute
  '/auth/events/create': typeof AuthEventsCreateLazyRoute
  '/auth/events/my': typeof AuthEventsMyLazyRoute
  '/auth/projects/$id': typeof AuthProjectsIdLazyRoute
  '/auth/projects/create': typeof AuthProjectsCreateLazyRoute
  '/auth/projects/my': typeof AuthProjectsMyLazyRoute
  '/auth/settings/notifications': typeof AuthSettingsNotificationsLazyRoute
  '/auth/settings/privacy': typeof AuthSettingsPrivacyLazyRoute
  '/auth/user/$username': typeof AuthUserUsernameLazyRoute
  '/auth/user/map': typeof AuthUserMapLazyRoute
  '/auth/user/profile': typeof AuthUserProfileLazyRoute
  '/auth/events': typeof AuthEventsIndexLazyRoute
  '/auth/projects': typeof AuthProjectsIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/auth/events': typeof AuthEventsRouteWithChildren
  '/auth/projects': typeof AuthProjectsRouteWithChildren
  '/auth/settings': typeof AuthSettingsRouteWithChildren
  '/auth/user': typeof AuthUserRouteWithChildren
  '/auth/feedback': typeof AuthFeedbackLazyRoute
  '/auth/home': typeof AuthHomeLazyRoute
  '/auth/messages': typeof AuthMessagesLazyRoute
  '/auth/search': typeof AuthSearchLazyRoute
  '/auth/support': typeof AuthSupportLazyRoute
  '/login/recover-password': typeof LoginRecoverPasswordLazyRoute
  '/login/reset-password': typeof LoginResetPasswordLazyRoute
  '/register/create-account': typeof RegisterCreateAccountLazyRoute
  '/login/': typeof LoginIndexRouteRoute
  '/auth/superadmin/dashboard': typeof AuthSuperadminDashboardRoute
  '/auth/events/$id': typeof AuthEventsIdLazyRoute
  '/auth/events/create': typeof AuthEventsCreateLazyRoute
  '/auth/events/my': typeof AuthEventsMyLazyRoute
  '/auth/projects/$id': typeof AuthProjectsIdLazyRoute
  '/auth/projects/create': typeof AuthProjectsCreateLazyRoute
  '/auth/projects/my': typeof AuthProjectsMyLazyRoute
  '/auth/settings/notifications': typeof AuthSettingsNotificationsLazyRoute
  '/auth/settings/privacy': typeof AuthSettingsPrivacyLazyRoute
  '/auth/user/$username': typeof AuthUserUsernameLazyRoute
  '/auth/user/map': typeof AuthUserMapLazyRoute
  '/auth/user/profile': typeof AuthUserProfileLazyRoute
  '/auth/events/': typeof AuthEventsIndexLazyRoute
  '/auth/projects/': typeof AuthProjectsIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/login'
    | '/auth/events'
    | '/auth/projects'
    | '/auth/settings'
    | '/auth/user'
    | '/auth/feedback'
    | '/auth/home'
    | '/auth/messages'
    | '/auth/search'
    | '/auth/support'
    | '/login/recover-password'
    | '/login/reset-password'
    | '/register/create-account'
    | '/login/'
    | '/auth/superadmin/dashboard'
    | '/auth/events/$id'
    | '/auth/events/create'
    | '/auth/events/my'
    | '/auth/projects/$id'
    | '/auth/projects/create'
    | '/auth/projects/my'
    | '/auth/settings/notifications'
    | '/auth/settings/privacy'
    | '/auth/user/$username'
    | '/auth/user/map'
    | '/auth/user/profile'
    | '/auth/events/'
    | '/auth/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth/settings'
    | '/auth/user'
    | '/auth/feedback'
    | '/auth/home'
    | '/auth/messages'
    | '/auth/search'
    | '/auth/support'
    | '/login/recover-password'
    | '/login/reset-password'
    | '/register/create-account'
    | '/login'
    | '/auth/superadmin/dashboard'
    | '/auth/events/$id'
    | '/auth/events/create'
    | '/auth/events/my'
    | '/auth/projects/$id'
    | '/auth/projects/create'
    | '/auth/projects/my'
    | '/auth/settings/notifications'
    | '/auth/settings/privacy'
    | '/auth/user/$username'
    | '/auth/user/map'
    | '/auth/user/profile'
    | '/auth/events'
    | '/auth/projects'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/login'
    | '/auth/events'
    | '/auth/projects'
    | '/auth/settings'
    | '/auth/user'
    | '/auth/feedback'
    | '/auth/home'
    | '/auth/messages'
    | '/auth/search'
    | '/auth/support'
    | '/login/recover-password'
    | '/login/reset-password'
    | '/register/create-account'
    | '/login/'
    | '/auth/superadmin/dashboard'
    | '/auth/events/$id'
    | '/auth/events/create'
    | '/auth/events/my'
    | '/auth/projects/$id'
    | '/auth/projects/create'
    | '/auth/projects/my'
    | '/auth/settings/notifications'
    | '/auth/settings/privacy'
    | '/auth/user/$username'
    | '/auth/user/map'
    | '/auth/user/profile'
    | '/auth/events/'
    | '/auth/projects/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRouteWithChildren
  RegisterCreateAccountLazyRoute: typeof RegisterCreateAccountLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRouteWithChildren,
  RegisterCreateAccountLazyRoute: RegisterCreateAccountLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.lazy.tsx",
      "children": [
        "/",
        "/auth",
        "/login",
        "/register/create-account"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/auth": {
      "filePath": "auth.tsx",
      "children": [
        "/auth/events",
        "/auth/projects",
        "/auth/settings",
        "/auth/user",
        "/auth/feedback",
        "/auth/home",
        "/auth/messages",
        "/auth/search",
        "/auth/support",
        "/auth/superadmin/dashboard"
      ]
    },
    "/login": {
      "filePath": "login.tsx",
      "children": [
        "/login/recover-password",
        "/login/reset-password",
        "/login/"
      ]
    },
    "/auth/events": {
      "filePath": "auth/events.tsx",
      "parent": "/auth",
      "children": [
        "/auth/events/$id",
        "/auth/events/create",
        "/auth/events/my",
        "/auth/events/"
      ]
    },
    "/auth/projects": {
      "filePath": "auth/projects.tsx",
      "parent": "/auth",
      "children": [
        "/auth/projects/$id",
        "/auth/projects/create",
        "/auth/projects/my",
        "/auth/projects/"
      ]
    },
    "/auth/settings": {
      "filePath": "auth/settings.tsx",
      "parent": "/auth",
      "children": [
        "/auth/settings/notifications",
        "/auth/settings/privacy"
      ]
    },
    "/auth/user": {
      "filePath": "auth/user.tsx",
      "parent": "/auth",
      "children": [
        "/auth/user/$username",
        "/auth/user/map",
        "/auth/user/profile"
      ]
    },
    "/auth/feedback": {
      "filePath": "auth/feedback.lazy.tsx",
      "parent": "/auth"
    },
    "/auth/home": {
      "filePath": "auth/home.lazy.tsx",
      "parent": "/auth"
    },
    "/auth/messages": {
      "filePath": "auth/messages.lazy.tsx",
      "parent": "/auth"
    },
    "/auth/search": {
      "filePath": "auth/search.lazy.tsx",
      "parent": "/auth"
    },
    "/auth/support": {
      "filePath": "auth/support.lazy.tsx",
      "parent": "/auth"
    },
    "/login/recover-password": {
      "filePath": "login/recover-password.lazy.tsx",
      "parent": "/login"
    },
    "/login/reset-password": {
      "filePath": "login/reset-password.lazy.tsx",
      "parent": "/login"
    },
    "/register/create-account": {
      "filePath": "register/create-account.lazy.tsx"
    },
    "/login/": {
      "filePath": "login/index.route.tsx",
      "parent": "/login"
    },
    "/auth/superadmin/dashboard": {
      "filePath": "auth/superadmin/dashboard.tsx",
      "parent": "/auth"
    },
    "/auth/events/$id": {
      "filePath": "auth/events/$id.lazy.tsx",
      "parent": "/auth/events"
    },
    "/auth/events/create": {
      "filePath": "auth/events/create.lazy.tsx",
      "parent": "/auth/events"
    },
    "/auth/events/my": {
      "filePath": "auth/events/my.lazy.tsx",
      "parent": "/auth/events"
    },
    "/auth/projects/$id": {
      "filePath": "auth/projects/$id.lazy.tsx",
      "parent": "/auth/projects"
    },
    "/auth/projects/create": {
      "filePath": "auth/projects/create.lazy.tsx",
      "parent": "/auth/projects"
    },
    "/auth/projects/my": {
      "filePath": "auth/projects/my.lazy.tsx",
      "parent": "/auth/projects"
    },
    "/auth/settings/notifications": {
      "filePath": "auth/settings/notifications.lazy.tsx",
      "parent": "/auth/settings"
    },
    "/auth/settings/privacy": {
      "filePath": "auth/settings/privacy.lazy.tsx",
      "parent": "/auth/settings"
    },
    "/auth/user/$username": {
      "filePath": "auth/user/$username.lazy.tsx",
      "parent": "/auth/user"
    },
    "/auth/user/map": {
      "filePath": "auth/user/map.lazy.tsx",
      "parent": "/auth/user"
    },
    "/auth/user/profile": {
      "filePath": "auth/user/profile.lazy.tsx",
      "parent": "/auth/user"
    },
    "/auth/events/": {
      "filePath": "auth/events/index.lazy.tsx",
      "parent": "/auth/events"
    },
    "/auth/projects/": {
      "filePath": "auth/projects/index.lazy.tsx",
      "parent": "/auth/projects"
    }
  }
}
ROUTE_MANIFEST_END */
